-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  description text NOT NULL,
  rating INTEGER NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('title1', 'www.1.com', 'description1', 1),
  ('title2', 'www.2.com', 'description2', 2),
  ('title3', 'www.3.com', 'description3', 3),
  ('title4', 'www.4.com', 'description4', 4),
  ('title5', 'www.5.com', 'description5', 1),
  ('title6', 'www.6.com', 'description6', 2),
  ('title7', 'www.7.com', 'description7', 3),
  ('title8', 'www.8.com', 'description8', 4),
  ('title9', 'www.9.com', 'description9', 1),
  ('title0', 'www.0.com', 'description0', 2);